services:

    nginx:
      build:
        context: docker
        dockerfile: dev/nginx/Dockerfile
      volumes:
        - ./app:/app
        - ./docker/dev/nginx/logs:/var/log/nginx
      ports:
        - "80:80"
      depends_on:
        - fpm

    fpm:
      build:
        context: docker
        dockerfile: dev/php-fpm/Dockerfile
      volumes:
        - ./app:/app
      environment:
        APP_DEBUG: ${APP_DEBUG}
        POSTGRES_HOST: ${POSTGRES_HOST}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_DB: ${POSTGRES_DB}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    cli:
      build:
        context: docker
        dockerfile: dev/php-cli/Dockerfile
      volumes:
        - ./app:/app
      environment:
        APP_DEBUG: ${APP_DEBUG}
        POSTGRES_HOST: ${POSTGRES_HOST}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_DB: ${POSTGRES_DB}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    postgresql:
      build:
        context: docker
        dockerfile: postgresql/Dockerfile
      environment:
        POSTGRES_HOST: ${POSTGRES_HOST}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_DB: ${POSTGRES_DB}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      volumes:
        - ./docker/postgresql/data:/var/lib/postgresql/data
      ports:
        - "5432:5432"

    #redis:
    #  image: redis:7.4-alpine
    #  volumes:
    #    - ./docker/redis/conf:/usr/local/etc/redis/redis.conf
    #    - ./docker/redis/data:/root/redis
    #  ports:
    #    - "6379:6379"






