controllers:
    resource:
        path: ../src/UI/Controller/
        namespace: App\UI\Controller
    type: attribute

api_login_check:
    path: /api/v1/auth/login

api_refresh_token:
    path: /api/v1/auth/refresh