security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Infrastructure\Persistence\Doctrine\Entity\DoctrineUser
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern: ^/api/v1/auth/login
            stateless: true
            json_login:
                check_path: api_login_check
                username_path: email
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        api_refresh_token:
            pattern: ^/api/v1/auth/refresh
            stateless: true
            refresh_jwt:
                check_path: api_refresh_token

        api:
            pattern: ^/api
            stateless: true
            jwt: ~


    access_control:
        #- { path: ^/api/v1/auth/login, roles: PUBLIC_ACCESS }
        #- { path: ^/api/v1/auth/protected, roles: IS_AUTHENTICATED_FULLY }
        #- { path: ^/api/v1/auth/refresh, roles: PUBLIC_ACCESS }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon
